CREATE TABLE IF NOT EXISTS users (
  user_id VARCHAR(255) NOT NULL PRIMARY KEY,
  user_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255),
  profile_pic VARCHAR(1000),
  phone_number VARCHAR(255),
  gender VARCHAR(255),
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
  cloudinary_image_public_id VARCHAR(255),
  provider VARCHAR(255) DEFAULT 'SELF',
  provider_user_id VARCHAR(255),
  email_token VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS contact (
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  phone_number VARCHAR(255),
  address VARCHAR(255),
  picture VARCHAR(255),
  description VARCHAR(1000),
  favorite BOOLEAN NOT NULL DEFAULT FALSE,
  website_link VARCHAR(255),
  linked_in_link VARCHAR(255),
  facebook_link VARCHAR(255),
  insta_link VARCHAR(255),
  cloudinary_image_public_id VARCHAR(255),
  user_user_id VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS social_link (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link VARCHAR(255),
  title VARCHAR(255),
  contact_id VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_role_list (
  user_user_id VARCHAR(255) NOT NULL,
  role_list VARCHAR(255),
  UNIQUE (user_user_id, role_list)
);

CREATE TABLE IF NOT EXISTS feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  review VARCHAR(1000),
  rating INT NOT NULL
);
